### PR TITLE
Rubocop, engage!

### PR DESCRIPTION
**Pull request by nerdinand**
Sorry for the huge PR, I couldn't help myself... ;-P
This takes us from almost 600 rubocop warnings down to 103. 
Next I'd like to look into test coverage and write some more tests, to enable safe refactorings further down the road.

Here's a summary of the remaining rubocop warnings:
```
41   Metrics/LineLength
29   Metrics/MethodLength
11   Metrics/AbcSize
10   Style/ClassAndModuleChildren
2    Metrics/ClassLength
2    Metrics/CyclomaticComplexity
2    Metrics/PerceivedComplexity
2    Style/IndentationConsistency
1    Lint/AssignmentInCondition
1    Lint/ElseLayout
1    Style/ExtraSpacing
1    Style/SpaceInsideParens
--
103  Total
```

Some of these are not so trivial to fix and will need some refactoring.

There are two warnings in particular, which look like actual bugs. Someone who knows the code better should have a look at them:

```
app/controllers/profiles_controller.rb:55:10: W: Odd else layout detected. Did you mean to use elsif?
    else current_profile
         ^^^^^^^^^^^^^^^
app/controllers/admin/tags_controller.rb:14:21: W: Assignment in condition - you probably meant to use ==.
    if existing_tag = ActsAsTaggableOn::Tag.where(name: params[:tag][:name]).first
                    ^
```

### CODE REVIEW

**Comment by tyranja** [comment]
Wow, thanks a lot!!!!!!!!!!!!

**Comment by nerdinand** [comment]
No worries, my pleasure! Hopefully I didn't break anything... :fearful:

**Comment by tyranja** [comment]
We will see :grin: I push it now to staging and later today to production.

**Comment by tyranja** [comment]
@nerdinand Thanks for pointing out the bugs. ( See comment of the PR) I changed the code accordingly.

**Pull request merged**
