### PR TITLE
Changed default value for 'willing to travel' and 'nonprofit' fields to true

### PR DESCRIPTION
**Pull request by alonpeer**
Followup to #1034 

CC @netagonen @tyranja

### CODE REVIEW

**Comment by tyranja** [comment]
Hups, I already wrote on a closed PR. Copy it here:

@alonpeer Actually, it would be better to leave it empty. Else we might give wrong estimates and people might get annoyed.

I discussed it here with Maren: https://github.com/rubymonsters/speakerinnen_liste/issues/1035

**Comment by alonpeer** [comment]
Ah, in that case we should make the distinction between `profile.willing_to_travel == false` and `profile.willing_to_travel == nil`, so that we can show those fields only when the value is `true` or `false`, but hide it when it's `nil`. This is not how it's currently implemented. I'll make another PR.

**Comment by tyranja** [comment]
Thank you @alonpeer and sorry for the confusion!

**Comment by alonpeer** [comment]
No worries :)

**Comment by alonpeer** [comment]
Replaced by #1040

**Pull request closed without merging**
