### PR TITLE
Ty new redirection for devise

### PR DESCRIPTION
**Pull request by tyranja**
Should work now. @zaziemo can you check? We could deploy it tomorrow. 

I just found out, that the twitter handle has not to be unique, that means different profiles can have one twitter handle. I am not sure whether that is a problem or not.

### CODE REVIEW

**Comment by zaziemo** [comment]
what is a little bit strange: if I sign in and I'm on the german locale, I get the english language success message "signed in!" . But all in all it works ;)

**Comment by tyranja** [comment]
I don't. :confounded: I hate that!!! :grimacing:

**Comment by tyranja** [comment]
Oh wait ...

**Comment by tyranja** [comment]
Oh nö. Still the same message ...

**Pull request merged**
