### PR TITLE
Su improve feature

### PR DESCRIPTION
**Pull request by sabrina-ulbrich**
Open questions: What's the "rails way" to add javascript from cdn? And second: I put the script at the end of the files. Do we use a separate direcory?

### CODE REVIEW

**Comment by tyranja** [comment]
First question: I don't know what cnd is, so :woman_shrugging: 
Second question: we do it both ways: https://github.com/rubymonsters/speakerinnen_liste/tree/master/app/assets/javascripts

or here: https://github.com/rubymonsters/speakerinnen_liste/tree/master/app/assets/javascripts

**Comment by tyranja** [comment]
@sabrina-ulbrich why do you use select2 now?

**Comment by sabrina-ulbrich** [comment]
@tyranja I tried to use tag-it for assigning profiles to features and didn't get it working (that doesn't mean it's impossible). So, I tried it the other way to use select2 for choosing and creating tags and it works. Goal was to use one plug-in for one task at two (maybe more) places. Now you can add profiles to features or features to profiles in the same way you choose tags, it's more comfortable.
Screen Shot 2019-03-31 at 17 47 16
Screen Shot 2019-03-31 at 17 48 09

What do you think?
cnd (content delivery network) is a way to get the code for javascripts, I used the recommendation from https://select2.org/getting-started/installation

**Comment by tyranja** [comment]
Cool. Find ich prima!

**Comment by tyranja** [comment]
Looks good! It is now much easier to add the profiles to the features in the feature admin dashboard.

**Comment by sabrina-ulbrich** [comment]
Screen Shot 2019-04-03 at 17 22 46
Unfortunately, the text is lower case (that only concerns the word "Feld"). Does it matter?
I like the second version with the placeholder better, which only appears if the field is empty. I don't get it working with differnet languages.
Screen Shot 2019-04-03 at 18 00 04
What do you mean @tyranja ?

**Comment by tyranja** [comment]
@sabrina-ulbrich I also like the second version better! Are you gonna merge after the change?

**Pull request merged**
