### PR TITLE
WIP: change title's family font

### PR DESCRIPTION
**Pull request by netagonen**
We said we want the titles to be the same font as text: changed it, looks awesome 
Screenshot from 2020-03-14 16-17-07

### CODE REVIEW

**Comment by zaziemo** [comment]
@netagonen you marked this PR as WIP. Is it still in progress?

**Comment by netagonen** [comment]
Not really, I marked it as WIP because I thought this is not decided and that we need to still discuss it. BUt if not, you can gladly merge it :)

**Comment by zaziemo** [comment]
@netagonen ok, then I think it would be cool to discuss it with @tyranja once she is back from holidays.

**Comment by zaziemo** [comment]
I will close this PR since I think we should decide upon those things in our new design process.

**Comment by netagonen** [comment]
cool! thanks

**Pull request closed without merging**
