### PR TITLE
Replace categories partial

### PR DESCRIPTION
**Pull request by netagonen**
Please review, also check if tests are enough

### CODE REVIEW

**Comment by tyranja** [comment]
https://guides.rubyonrails.org/v5.2/caching_with_rails.html#low-level-caching there is the link, I am not sure if it is helpfull.

**Comment by netagonen** [comment]
I changed the memoization to caching. now the method from the categories helper can be used in other classes and it's cached!
in our case these are the differences between the methods:
- memoization: query will run with every new request
- basic rails cache: data becomes stale until cache expires if new profiles are updated
To me it seems fine to go with the cache, the 1 hour expiration could be also changed to what seems reasonable for you. 
The `categories_helper` can be included in whatever controller and the `category_profiles_count(category_id)` method will give the number of profiles per `category.id`. this could be refactored of course if you want it in the controller, but then you should make sure the `categories_partial` still works.

**Comment by tyranja** [comment]
I have added underlines to the category links to make it more visible that they are links

**Comment by tyranja** [comment]
IT IS MERGED!!!! Thanks a lot @netagonen!!!!!

**Pull request merged**
