### PR TITLE
Some work on adding slugs to profiles

### PR DESCRIPTION
**Pull request by marcinwyszynski**
Hey there,

bedtime story time is over so I managed to finish this unit of work. I implemented friendly URLs for Profiles essentially composed of first and last name and a random number should there ever be a duplicate. At the moment as a user you can't choose that yourself. This isn't necessarily the best idea either because it could invalidate old URLs. All specs are passing - only one required a gentle squeeze.

While getting this app to work I fixed one bad migration and - more importantly - added a Docker container and a docker-compose file so that it is easier for folks to get started next time with all the dependencies already in place.

Best,
Marcin

[Review on Reviewable](https://reviewable.io/reviews/rubymonsters/speakerinnen_liste/403)

### CODE REVIEW

**Comment by tyranja** [comment]
Thanks @marcinwyszynski!!! :star: :star:  :star:  And thank you child for sleeping so you can code! :sleeping:

**Comment by zaziemo** [comment]
Hey @marcinwyszynski, thanks a lot for you work! 
I have a question. Currently the slug creation doesn't behave as I expected (FirstnameLastname). It seems only to consist of the random part, e.g. 6a5b6. Could you check that? And it would be great to have a spec that makes sure that the slug is created as expected and also that the default rails routing (to the ID) stays in place.

**Comment by zaziemo** [comment]
Hey @marcinwyszynski do you have some minutes to answer the question :) ?

**Comment by marcinwyszynski** [comment]
I'll have a look at it later on today or tomorrow. I was under the impression that both first and last name will be used _if they are set_.

**Comment by zaziemo** [comment]
@marcinwyszynski thx a lot for checking that out. That is also what I expected but with my data it doesn't work like this.

**Comment by marcinwyszynski** [comment]
@zaziemo I added specs that prove my theory. Essentially it was correct - slug will use `firstname` and `lastname` but if these are not set it just uses the last, random part. If you validate the presence of both fields this should never cause a problem. I also added a spec to verify that you can use ids and slugs interchangeably in URLs.

**Comment by zaziemo** [comment]
@marcinwyszynski cool, thanks for the specs. I think the problem is, that the logic of the slug creation doesn't match the logic of registring a profile. 

When a new user creates a profile: 
1) she is only able to enter an email adress
2) then she has to confirm the account 
3) and only in the next step she can enter her name.

The slug is presumably created in the first step where no name is provided yet. What about creating slugs only for profiles that have names provided? This should be possible easily possible, what do you think?

**Comment by marcinwyszynski** [comment]
> What about creating slugs only for profiles that have names provided? This should be possible easily possible, what do you think?

Unfortunately, it would be neither easy, nor desirable. There are two things going on here. The first one is that slugs are generated on resource _creation_. Of course it's only software and we can hack it to *re*create slugs under certain circumstances - ie. when first name and/or last name change but there is a more fundamental philosophical question there. Namely, slugs are like IDs in a way that they are meant to uniquely identify resources and persist between resource changes. If we start recreating these slugs willy-nilly then we'll end up with dead URLs sooner or later.

**Comment by zaziemo** [comment]
@marcinwyszynski yes I know that unique identifier principle. And I don't want to change that. I thought it might only be possible NOT to create any slug if there is NO name provided. As soon as there is one, slug is created and never changed afterwards. 
If this isn't possible we can only make the slugs in that context really working if we set the name fields as mandatory already in the first step of the registration process, right!?

**Comment by zaziemo** [comment]
was implemented by @tyranja <3

**Pull request closed without merging**
