### PR TITLE
Add the speakerin count in cats

### PR DESCRIPTION
**Pull request by tyranja**
Add titles to the category bars
Add a empty box for register as a speaker

### CODE REVIEW

**Comment by tyranja** [comment]
@athomschke It looks now like this. I have no idea how the make the text float in the center of the box and make the box square. Can you hep me with that?

Screenshot from 2021-02-08 16-34-24

**Comment by athomschke** [comment]
Will have a look!

**Comment by athomschke** [comment]
Slowly making progress - what's missing is making the box responsive now. Salit noted on Monday that it would be nice to have the box always green, not only on hover - capturing this callout here, mainly as a reminder to self.

**Comment by athomschke** [comment]
Note to self: found out what causes the "it's not square" issue we see on staging, it happens when profiles in the same line have a two-liner as their main focus. Working on it.

**Comment by tyranja** [comment]
Thank you @athomschke :)

**Pull request merged**
