### PR TITLE
Ty correct search

### PR DESCRIPTION
**Pull request by tyranja**
- Removes a not used search model
- Adds and corrects rspec search tests
- Removes a unit test because we want to switch to rspec tests altogether
- Adds "ANY" to the search to get correct search results (see test:  spec/features/searching_for_profiles_spec.rb line 17 )

@svenfuchs can you maybe have a look at that last point with the search: app/models/profiles_search.rb   
I just looked that up it the internet :/

### CODE REVIEW

**Comment by zaziemo** [comment]
Hey @tyranja, 
In my local database I have two profiles:
Profile 1
firstname: Simone
lastname: Müller
Twitter: moni

Profile 2
firstname: Maren
lastname: Heltsche
Twitter: zaziemo

If I look after Simone Zaziemo I get both profiles as a result. What I was expecting, was no match because there is no Simone with a twitter handle zaziemo.
As a (Google?) user I expect to use the AND operator by default. What I now get is the OR.  
I am not sure if the problem is the ANY operator in profiles_search.rb.

Probably we should have a look on textacular together on monday: https://textacular.github.io/textacular/

**Comment by zaziemo** [comment]
Hum @tyranja, strange: 
- if I search Simone Müller I get a result (which is cool)
- if I search Maren Heltsche I get no result (which is not cool because the profile is there)

**Comment by tyranja** [comment]
Did you checked it local? Because there it works fine on my computer.

**Comment by zaziemo** [comment]
yes, locally on my machine.

**Pull request merged**
