### PR TITLE
Delete unused code

### PR DESCRIPTION
**Pull request by sabrina-ulbrich**
For information: If I create the file schema.rb after migration, then the attribute for strings "limit: 255" is not made. This regularly leads to annoying merge conflicts. Can we handle this?

### CODE REVIEW

**Comment by tyranja** [comment]
@sabrina-ulbrich Since the PR for adding the websites ( https://github.com/rubymonsters/speakerinnen_liste/pull/723 ) is merged, there are some merge conflicts with master now.

**Comment by sabrina-ulbrich** [comment]
@tyranja can we solve the merge conflicts together? I feel doubtful when I am alone with that.

**Comment by tyranja** [comment]
@sabrina-ulbrich Sorry, did not see your comment. I have to turn the notifications back on. But it looks like you have done it :tada:

**Comment by sabrina-ulbrich** [comment]
Should I press the great green merge button or does anybody want to have a look at the code, @zaziemo @tyranja ?

**Comment by tyranja** [comment]
Can we delete that line:  `include AutoHtml` in the beginning of the profile model as well?

**Comment by tyranja** [comment]
other than that, it looks :+1:

**Comment by sabrina-ulbrich** [comment]
@tyranja Yes, done it. It seems to belong to the medialink class now.

**Comment by zaziemo** [comment]
Yes, do it :)

**Pull request merged**
