### PR TITLE
add website 2 and 3 to profiles [#238]

### PR DESCRIPTION
**Pull request by sabrina-ulbrich**

### CODE REVIEW

**Comment by sabrina-ulbrich** [comment]
Thanks for the feedback @tyranja :) I've done this.

**Comment by tyranja** [comment]
Ha, after adding another test similiar to the one in profile editing I even found out that we missed a field in the admin show view :roll_eyes: Good to have good tests :)

**Comment by sabrina-ulbrich** [comment]
👍

**Comment by tyranja** [comment]
I have changed some of the view so it looks like that now:

In profile show with different amount of websites added:

show_en
show_en_1
show3_de

In profile edit:
edit_de

**Comment by zaziemo** [comment]
Some thoughts:
- how do we handle fallbacks? Currently when I enter 2 websites in my german profile, these 2 websites are shown in the :de and :en locale. When I enter 1 website in my english profile, this website is shown in the :en locale but the second website from the german profile still shows up. 
--> Suggestion if possible: use fallback only when no website is given

- @sabrina-ulbrich I can't reproduce your bug you mention above. Is it still a problem?

**Comment by tyranja** [comment]
Do you mean use the fall-back only when no website in that language is given at all?

I have changes the code now that way:


When only the **first website in one language** is provided: 
- use normal fall-back

When only the **first website and one of the additional websites in one language** is provided:
- the first website uses normal fall-back
- the other is only shown in their language ( no fall-back )

When the **first website is in both language there and one of the additional websites** in one language:
- the first website in both languages
- the other are only shown in their language ( no fall-back )

That means the 2 additional languages have no fall-back option. 

How does that sound?

**Comment by tyranja** [comment]
@zaziemo could yo have a look at it today?

**Comment by tyranja** [comment]
New behaviour now:

**no website** in current language scope: 
 - use fall-back

**at least one website** in current language scope: 
- don't use fall-back for all the other websites


Here is the test:

```
  describe 'globalize fall-back options for websites' do
    before do
      sign_in ada
      click_on 'EN', match: :first
    end

    it 'when there is no website given for the current language scope you are in use the fall-back' do
      expect(page).to have_content('www.ada.de')
      expect(page).to have_content('www.ada2.de')
      expect(page).to have_content('www.ada3.de')
      click_on 'DE', match: :first
      expect(page).to have_content('www.ada.de')
      expect(page).to have_content('www.ada2.de')
      expect(page).to have_content('www.ada3.de')
    end

    it 'when there is at least one website given for the current language dont use fall-back' do
      ada.website_en = "www.ada.en"
      ada.website_2_en = "www.ada2.en"
      ada.save!
      visit current_path
      expect(page).to have_content('www.ada.en')
      expect(page).to have_content('www.ada2.en')
      expect(page).not_to have_content('www.ada3.de')
      click_on 'DE', match: :first
      expect(page).to have_content('www.ada.de')
      expect(page).to have_content('www.ada2.de')
      expect(page).to have_content('www.ada3.de')
    end
  end
```

**Comment by zaziemo** [comment]
Yay, great work @sabrina-ulbrich @tyranja ❤️🌈🙌🏼

**Pull request merged**
